
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path"
import "dotenv/config";
import { defineConfig, env } from "prisma/config";


dotenv.config({ path: path.resolve(__dirname, "../../apps/web/.env")})

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
